#!/bin/bash

# can't pass the 'source' results outside this script (without starting a sub-shell), so just use it here.
source .env/Scripts/activate

# pass through all args: https://stackoverflow.com/questions/3811345/how-to-pass-all-arguments-passed-to-my-bash-script-to-a-function-of-mine
./src/todo.py "$@"
